name: exploring workflow events and activity types

on:
    workflow_dispatch: 
    
    # schedule:
    #     - cron: "*/59 * * * *"
    
    push:
        branches: 
            - main
            - '!feature/*'    # ignoring pushing to any branch name starting with feature using ! (not)
        # branches-ignore: 
        #     - feature/*     # ignore feature/add-music, feature/updateImages etc
        #     - test/**       # ignore test/ui/index, test/checkout/payment etc

    pull_request: 
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.md     # workflow will only run when a pull request that includes a change on any file other than README.md
        branches: 
            - main          # configures your workflow to only run on pull requests that target specific branches

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Show what event type the workflow is triggered
              run: echo This workflow/job/step is executed for event type - ${{ github.event_name }}
