name: my first action

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v4

    - name: List and Read files
      run: |
        echo "My first GitHub Action step"
        ls -ltra
        cat README.md

    # - name: List files
    #   run: ls

    # - name: Read file
    #   run: cat README.md