name: Generate ASCII

on: push

jobs:
  generate-ascii-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: checkout/actions@v4

    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsays CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON... Rawr!!!" >> dragon.txt

    - name: Test file exists
      run: grep -i "dragon" dragon.txt

    - name: Read file
      run: cat dragon.txt

    - name: List repo files
      run: ls -la