name: Multi Job Workflow Demo

on: 
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y
  
    - name: Execute cowsays CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON... Rawr!!!" >> dragon.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dragon-txt-file
        path: dragon.txt

  test_job_1:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-txt-file

    - name: Test file exists
      run: grep -i "dragon" dragon.txt

  deploy_job_1:
    needs: [test_job_1]
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact file
      uses: actions/download-artifact@v4
      with:
        name: dragon-txt-file

    - name: Read file
      run: cat dragon.txt
      
    - name: Deploy
      run: echo Deploying......
