name: Exploring Variables and Secrets (STEP level)

on: workflow_dispatch

jobs:
################### environment variables at STEP level ###################
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: girishmatta7
                IMAGE_NAME: github-actions-nginx
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker Login
              env: 
                DOCKER_USERNAME: girishmatta7
                DOCKER_PASSWORD: Pa$$w0rd1
              run: echo docker login --username=${{ env.DOCKER_USERNAME }} --password=${{ env.DOCKER_PASSWORD }}

            - name: Docker Publish
              run: echo docker push docker.io/dockerUserName/imageName:latest

    deploy:
        needs: [docker]
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              env: 
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: girishmatta7
                IMAGE_NAME: github-actions-nginx
              run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
