name: Exploring Variables and Secrets

on: workflow_dispatch

################### environment variables at WORKFLOW level ###################
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: girishmatta7
  IMAGE_NAME: github-actions-nginx

jobs:

    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

            - name: Docker Login
              env:
                DOCKER_PASSWORD: Pa$$w0rd1
                TEST_VAR: test
              run: docker login --username=${{ env.DOCKER_USERNAME }} --password=${{ env.IMAGE_NAME }}

            - name: Docker Publish
              run: docker push docker.io/dockerUserName/imageName:latest

    deploy:        
        needs: [docker]
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME}}:latest
